server:
  port: 8088
  #  http:
  #    port: 8008
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://mongodb_notification:dinhanst2832004@localhost:27019/notification_db?authSource=notification_db
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: yunomix2834@gmail.com
    password: mfym xcpi cstr ckfd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  event:
    notification-events: "notification-events"