server:
  port: 8080
  #  http:
  #    port: 8000
  servlet:
    context-path: /identity
#  ssl:
#    enabled: true
#    key-alias: identity-https
#    key-store: classpath:ssl/identity.jks
#    key-store-type: JKS
#    key-store-password: dinhanst2832004
#    key-password: dinhanst2832004

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5431/identity_db
    username: postgres_identity
    password: dinhanst2832004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        session_factory.interceptor: com.codecampus.identity.configuration.audit.SoftDeleteInterceptor
        envers:
          revision_on_collection_change: true
          store_data_at_delete: true # Lưu dữ liệu khi xóa
          global_with_modified_flag: true # Đánh dấu trường thay đổi
          audit_table_suffix: _aud # Hậu tố bảng audit
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yunomix2834@gmail.com
    password: mfym xcpi cstr ckfd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  services:
    profile: http://localhost:8081/profile
  otp:
    expiry-minutes: 5
  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds
  google:
    client-id: "989048331981-ftq9jst7r5os4fc0u64ongvsp08fvka1.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:4200/auth/identity/authenticate"

