server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:postgresql://identity-db:5432/${IDENTITY_DATABASE}
    username: ${IDENTITY_USERNAME}
    password: ${IDENTITY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true

app:
  services:
    profile: http://profile-service:8081/profile
    organization: http://organization-service:8092/org
  init:
    admin:
      username: ${INIT_ADMIN_USERNAME:}
      password: ${INIT_ADMIN_PASSWORD:}
      email: ${INIT_ADMIN_EMAIL:}
    teacher:
      username: ${INIT_TEACHER_USERNAME:}
      password: ${INIT_TEACHER_PASSWORD:}
      email: ${INIT_TEACHER_EMAIL:}
    student:
      username: ${INIT_STUDENT_USERNAME:}
      password: ${INIT_STUDENT_PASSWORD:}
      email: ${INIT_STUDENT_EMAIL:}
    tempPassword: ${TEMP_PASSWORD}
