server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:



app:
  services:
    profile: http://localhost:8081/profile
  jwt:
    key-secret:
      "code-campus-123456"
    expiration: 3