name: codecampus

services:
  # ---------- PostgreSQL ----------
  identity-db:
    image: bitnami/postgresql:latest
    container_name: identity-db
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=${IDENTITY_USERNAME}
      - POSTGRESQL_PASSWORD=${IDENTITY_DB_PASSWORD}
      - POSTGRESQL_DATABASE=identity_db
      - POSTGRESQL_POSTGRES_PASSWORD=${IDENTITY_DB_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - identity_pg_data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ backend ]

  quiz-db:
    image: bitnami/postgresql:latest
    container_name: quiz-db
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=${QUIZ_USERNAME}
      - POSTGRESQL_PASSWORD=${QUIZ_DB_PASSWORD}
      - POSTGRESQL_DATABASE=quiz_db
      - POSTGRESQL_POSTGRES_PASSWORD=${QUIZ_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - quiz_pg_data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ backend ]

  submission-db:
    image: bitnami/postgresql:latest
    container_name: submission-db
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=${SUBMISSION_USERNAME}
      - POSTGRESQL_PASSWORD=${SUBMISSION_DB_PASSWORD}
      - POSTGRESQL_DATABASE=submission_db
      - POSTGRESQL_POSTGRES_PASSWORD=${SUBMISSION_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - submission_pg_data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ backend ]

  # ----------  Redis (master-replica)  ----------
  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/bitnami/redis/data
    networks: [ backend ]

  redis-replica:
    image: bitnami/redis:latest
    container_name: redis-replica
    restart: unless-stopped
    depends_on: [ redis-master ]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "6380:6379"
    volumes:
      - redis_replica_data:/bitnami/redis/data
    networks: [ backend ]

  # ----------  Kafka  ----------
  kafka:
    image: bitnami/kafka:latest               # ghim tag cố định nếu muốn
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # — listener bên trong cluster
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      # — hostname quảng bá cho client (service khác)
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://${HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER="yes"         # chỉ dev
    ports:
      - "9092:29092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks: [ backend ]
  
  # ---------- Neo4j ----------
  neo4j:
    image: bitnami/neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_DAEMON_USER=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - INIT_NEO4J_PASSWORD=${NEO4J_PASSWORD}
      # Mở cổng Bolt & HTTP
      - NEO4J_BOLT_PORT_NUMBER=7687
      - NEO4J_HTTP_PORT_NUMBER=7474
      # Lắng nghe trên mọi IP
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/bitnami/neo4j
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p $${NEO4J_PASSWORD} 'RETURN 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ backend ]

networks:
  backend:

volumes:
  identity_pg_data:
  submission_pg_data:
  quiz_pg_data:
  redis_master_data:
  redis_replica_data:
  kafka_data:
  neo4j_data: