name: codecampus
services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=dinhanst2832004
      - POSTGRESQL_DATABASE=identity_db
      - POSTGRESQL_POSTGRES_PASSWORD=dinhanst2832004
    ports:
      - "5431:5432" # host:container
    volumes:
      - pg_data:/bitnami/postgresql # dữ liệu bền vững
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: bitnami/neo4j
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_DAEMON_USER=neo4j
      - NEO4J_PASSWORD=dinhanst2832004
      - NEO4J_BOLT_PORT_NUMBER=7687 # cổng trong container
      # Mở REST UI
      - NEO4J_HTTP_PORT_NUMBER=7474
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
    ports:
      - "7689:7687" # host:container (BOLT)
      - "7474:7474"
    volumes:
      - neo4j_data:/bitnami/neo4j # dữ liệu bền vững
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p $${NEO4J_PASSWORD} 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
  neo4j_data: