spring:
  datasource:
    url: jdbc:postgresql://organization-db:5432/${ORGANIZATION_DATABASE}
    username: ${ORGANIZATION_USERNAME}
    password: ${ORGANIZATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: http://kafka:9092
  data:
    redis:
      host: redis     # dịch vụ trong compose
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  services:
    file: http://file-service:8082/file
    profile: http://profile-service:8081/profile