spring:
  datasource:
    url: jdbc:postgresql://organization-db:5432/${ORGANIZATION_DATABASE}
    username: ${ORGANIZATION_USERNAME}
    password: ${ORGANIZATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: http://kafka:9092

app:
  services:
    file: http://file-service:8082/file