file:
  service:
    file-url: http://file-service:8082

spring:
  datasource:
    url: jdbc:postgresql://post-db:5432/${POST_DATABASE}
    username: ${POST_USERNAME}
    password: ${POST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: http://kafka:9092
  data:
    redis:
      host: redis     # dịch vụ trong compose
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  services:
    profile: http://profile-service:8081/profile
    file: http://file-service:8082/file
