server:
  port: 8090
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    url: jdbc:postgresql://localhost:5439/post_db
    username: postgres_post
    password: dinhanst2832004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      acks: all
  #      retries: 3
  #      # optional: giảm latency
  #      linger-ms: 5            # gộp record <= 5 MS rồi mới gửi
  #      batch-size: 16384       # 16 KB
  #      compression-type: lz4   # nén nhẹ – giảm băng thông
  data:
    redis:
      host: localhost # dịch vụ trong compose
      port: 6379
      password: dinhanst2832004
      timeout: 3000ms

app:
  services:
    profile: http://localhost:8081/profile
    file: http://localhost:8082/file
  event:
    profile-events: "profile-events"