server:
  port: 8090
  servlet:
    context-path: /post
  ssl:
    enabled: true
    key-store: classpath:ssl/post.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: post-https
    client-auth: need
    trust-store: classpath:ssl/truststore.p12
    trust-store-type: PKCS12
    trust-store-password: changeit

spring:
  application:
    name: post-service
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    url: jdbc:postgresql://localhost:5439/post_db
    username: postgres_post
    password: dinhanst2832004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      acks: all
  #      retries: 3
  #      # optional: giảm latency
  #      linger-ms: 5            # gộp record <= 5 MS rồi mới gửi
  #      batch-size: 16384       # 16 KB
  #      compression-type: lz4   # nén nhẹ – giảm băng thông
  data:
    redis:
      host: localhost # dịch vụ trong compose
      port: 6379
      password: dinhanst2832004
      timeout: 3000ms

app:
  services:
    profile: https://localhost:8081/profile
    file: https://localhost:8082/file
    identity: https://localhost:8080/identity
  event:
    profile-events: "profile-events"
    post-events: "post-events"
    post-access-events: "post-access-events"