server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - name: RateLimiter
              args:
                routeId: identity_service
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
            - name: RateLimiter
              args:
                routeId: profile_service
# Cấu hình rate limiter
rate-limiter:
  default:
    capacity: 10
    refillTokens: 10
    refillDuration: 60
  routes:
    identity_service: # Khớp với routeId
      capacity: 20
      refillTokens: 20
      refillDuration: 60
    profile_service: # Khớp với routeId
      capacity: 20
      refillTokens: 20
      refillDuration: 60