server:
  port: 8888
  ssl:
    key-alias: gateway-https
    key-store: classpath:gateway.jks
    key-store-type: JKS
    key-password: dinhanst2832004

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - name: RateLimiter
              args:
                routeId: identity_service

# Cấu hình rate limiter
rate-limiter:
  default:
    capacity: 10
    refillTokens: 10
    refillDuration: 60
  routes:
    identity_service: # Khớp với routeId
      capacity: 20
      refillTokens: 20
      refillDuration: 60