server:
  http_listen_port: 0
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # Đọc file log JSON của Docker
  - job_name: docker-logs
    pipeline_stages:
      - docker: { }   # parse log docker JSON
    static_configs:
      - targets: [ localhost ]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

  # (tuỳ chọn) Khám phá container qua Docker socket để thêm nhãn từ label
  - job_name: docker-sd
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [ '__meta_docker_container_name' ]
        target_label: 'container'
      - source_labels: [ '__meta_docker_container_label_com_docker_compose_service' ]
        target_label: 'service'
