server:
    port: 8091
    servlet:
        context-path: /payment


spring:
  application:
    name: payment-service
  datasource:
      url: jdbc:postgresql://localhost:5440/payment_db
      username: postgres_payment
      password: dinhanst2832004
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    openfeign:
        multipart:
            enabled: true

app:
    services:
        profile: http://localhost:8081/profile
        file: http://localhost:8082/file
        organization: http://localhost:8091/org


