server:
  port: 8086
  #  http:
  #    port: 8006
  servlet:
    context-path: /ai
  tomcat:
    # Ngăn Tomcat chặn nuốt request lớn (giữ nguyên dữ liệu lớn)
    max-swallow-size: -1
#  ssl:
#    enabled: true
#    key-alias: ai-https
#    key-store: classpath:ssl/ai.jks
#    key-store-type: JKS
#    key-store-password: dinhanst2832004
#    key-password: dinhanst2832004

spring:
  application:
    name: ai-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      # Cho phép Spring Boot phục vụ cả classpath:/static/ và thư mục ngoài ./uploads/
      static-locations: classpath:/static/, file:./uploads/
  datasource:
    url: jdbc:postgresql://localhost:5436/ai_db
    username: postgres_ai
    password: dinhanst2832004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  ai:
    openai:
      # Hard code để test
      api-key: AIzaSyB70AASubd5jiecmWY5NFnfPaGwe0nauUk
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 10000

app:
  services:
    submission: http://localhost:8083/submission
  file:
    upload-dir: ./uploads
