server:
  port: 8087
  servlet:
    context-path: /search
  ssl:
    enabled: true
    key-store: classpath:ssl/search.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: search-https
    client-auth: need
    trust-store: classpath:ssl/truststore.p12
    trust-store-type: PKCS12
    trust-store-password: changeit

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://localhost:9200
    username: elasticsearch_search
    password: dinhanst2832004
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: localhost # dịch vụ trong compose
      port: 6379
      password: dinhanst2832004
      timeout: 3000ms

app:
  event:
    exercise-events: "exercise-events"
    user-registrations: "user-registrations"
    user-events: "user-events"
    profile-events: "profile-events"
    post-events: "post-events"
    post-access-events: "post-access-events"
    organization-events: "organization-events"
    exercise-purchased-events: "exercise-purchased-events"
  services:
    profile: https://localhost:8081/profile
    post: https://localhost:8090/post
    organization: https://localhost:8092/org