spring:
  elasticsearch:
    uris: http://elasticsearch:9200
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    socket-timeout: 30s
    connection-timeout: 10s
  lifecycle:
    timeout-per-shutdown-phase: 20s
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: redis     # dịch vụ trong compose
      port: 6379
      password: ${REDIS_PASSWORD}

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch.client: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true

app:
  services:
    profile: http://profile-service:8081/profile
    post: http://post-service:8090/post
    organization: http://organization-service:8092/org