server:
  port: 8081
  #  http:
  #    port: 8001
  servlet:
    context-path: /profile
#  ssl:
#    enabled: true
#    key-alias: profile-https
#    key-store: classpath:ssl/profile.jks
#    key-store-type: JKS
#    key-store-password: dinhanst2832004
#    key-password: dinhanst2832004

spring:
  application:
    name: profile-service
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: dinhanst2832004
    schema-action: create

app:
  services:
    file: http://localhost:8082/file

