server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  neo4j:
    uri: neo4j://neo4j:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

app:
  services:
    file: http://file-service:8082/file
    organization: http://organization-service:8091/org

