server:
  port: 8085
  http:
    port: 8005
  servlet:
    context-path: /quiz

grpc:
  client:
    submissionGrpc:
      address: static://submission-service:9090
      negotiationType: plaintext
  server:
    port: 9090

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://localhost:5433/quiz_db
    username: postgres_quiz
    password: dinhanst2832004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: redis-master     # dịch vụ trong compose
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.codecampus.*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
  topic:
    exercise-created: exercise.created