server:
  port: 8084
  #  http:
  #    port: 8004
  servlet:
    context-path: /coding
#  ssl:
#    enabled: true
#    key-alias: coding-https
#    key-store: classpath:ssl/coding.jks
#    key-store-type: JKS
#    key-store-password: dinhanst2832004
#    key-password: dinhanst2832004

grpc:
  server:
    port: 9592

submission:
  grpc:
    host: localhost
    port: 9590

playground:
  grpc:
    host: localhost
    port: 9593

spring:
  application:
    name: coding-service
  datasource:
    url: jdbc:postgresql://localhost:5435/coding_db
    username: postgres_coding
    password: dinhanst2832004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: localhost     # dịch vụ trong compose
      port: 6379
      password: dinhanst2832004
      timeout: 3000ms