server:
  port: 8089
  servlet:
    context-path: /chat

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://${CHAT_USERNAME}:${CHAT_PASSWORD}@chat-db:27017/${CHAT_DATABASE}?authSource=${CHAT_DATABASE}
      auto-index-creation: true
    redis:
      host: redis     # dịch vụ trong compose
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: http://kafka:9092

app:
  services:
    profile: http://profile-service:8081/profile
    identity: http://identity-service:8080/identity
    file: http://file-service:8082/file