server:
  port: 8089
  servlet:
    context-path: /chat
  ssl:
    enabled: true
    key-store: classpath:ssl/chat.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: chat-https
    client-auth: need
    trust-store: classpath:ssl/truststore.p12
    trust-store-type: PKCS12
    trust-store-password: changeit

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://mongodb_chat:dinhanst2832004@localhost:27019/chat_db?authSource=chat_db
      auto-index-creation: true
    redis:
      host: localhost # dịch vụ trong compose
      port: 6379
      password: dinhanst2832004
      timeout: 3000ms
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
app:
  event:
    profile-events: "profile-events"
  services:
    profile: https://localhost:8081/profile
    identity: https://localhost:8080/identity
    file: https://localhost:8082/file