name: Build & Push file-service

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'FileService/**'
      - 'docker/file-service.Dockerfile'
      - '.github/workflows/file-service-publish.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-file-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive IMAGE_TAG
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA::12}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push file-service
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          DOCKER_PLATFORMS: linux/amd64
        run: |
          chmod +x ./build-image-file.sh
          ./build-image-file.sh
